# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gym_rl.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gym_rl.proto',
  package='gym_rl',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0cgym_rl.proto\x12\x06gym_rl\"\xc6\x02\n\rOfflineRlInfo\x12\x0f\n\x07\x66\x65\x61ture\x18\x01 \x01(\x0c\x12\x14\n\x0cnext_feature\x18\x02 \x01(\x0c\x12\x0e\n\x06reward\x18\x03 \x01(\x01\x12\x0c\n\x04\x64one\x18\x04 \x01(\x05\x12\r\n\x05value\x18\x05 \x01(\x01\x12\x13\n\x0bneg_log_pis\x18\x06 \x01(\x01\x12\x13\n\x0b\x61\x63tion_list\x18\x07 \x03(\x05\x12\x11\n\tadvantage\x18\x08 \x01(\x01\x12\x12\n\nreward_sum\x18\t \x01(\x01\x12\x0f\n\x07game_id\x18\n \x01(\x0c\x12\x10\n\x08is_train\x18\x0b \x01(\x08\x12\x14\n\x0cis_game_over\x18\x0c \x01(\x05\x12\x0e\n\x06\x61\x63tion\x18\r \x01(\x05\x12\x0c\n\x04uuid\x18\x0f \x01(\x0c\x12\x14\n\x0cnext_Q_value\x18\x10 \x01(\x0c\x12\x11\n\tgamma_pow\x18\x11 \x01(\x01\x12\x10\n\x08\x66rame_no\x18\x12 \x01(\x05')
)




_OFFLINERLINFO = _descriptor.Descriptor(
  name='OfflineRlInfo',
  full_name='gym_rl.OfflineRlInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='feature', full_name='gym_rl.OfflineRlInfo.feature', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='next_feature', full_name='gym_rl.OfflineRlInfo.next_feature', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reward', full_name='gym_rl.OfflineRlInfo.reward', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='done', full_name='gym_rl.OfflineRlInfo.done', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='gym_rl.OfflineRlInfo.value', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='neg_log_pis', full_name='gym_rl.OfflineRlInfo.neg_log_pis', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action_list', full_name='gym_rl.OfflineRlInfo.action_list', index=6,
      number=7, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='advantage', full_name='gym_rl.OfflineRlInfo.advantage', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reward_sum', full_name='gym_rl.OfflineRlInfo.reward_sum', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='game_id', full_name='gym_rl.OfflineRlInfo.game_id', index=9,
      number=10, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_train', full_name='gym_rl.OfflineRlInfo.is_train', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_game_over', full_name='gym_rl.OfflineRlInfo.is_game_over', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action', full_name='gym_rl.OfflineRlInfo.action', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='gym_rl.OfflineRlInfo.uuid', index=13,
      number=15, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='next_Q_value', full_name='gym_rl.OfflineRlInfo.next_Q_value', index=14,
      number=16, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gamma_pow', full_name='gym_rl.OfflineRlInfo.gamma_pow', index=15,
      number=17, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frame_no', full_name='gym_rl.OfflineRlInfo.frame_no', index=16,
      number=18, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=351,
)

DESCRIPTOR.message_types_by_name['OfflineRlInfo'] = _OFFLINERLINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OfflineRlInfo = _reflection.GeneratedProtocolMessageType('OfflineRlInfo', (_message.Message,), {
  'DESCRIPTOR' : _OFFLINERLINFO,
  '__module__' : 'gym_rl_pb2'
  # @@protoc_insertion_point(class_scope:gym_rl.OfflineRlInfo)
  })
_sym_db.RegisterMessage(OfflineRlInfo)


# @@protoc_insertion_point(module_scope)
